name: Build and publish images

on:
  push:
    branches:
      - master
      - dev-master
    # paths:
    #   - .github/workflows/publish-image.yml
    #   - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - "bookworm-slim"
          - "bullseye-slim"
          - "buster-slim"
        include:
          - latest: false
          - latest: true
            release: "bookworm-slim"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and publish
        uses: ./.github/actions/build-image
        with:
          image: ${{ vars.IMAGE_NAME }}
          release: ${{ matrix.release }}
          latest: ${{ matrix.latest }}
          push: false
          docker-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
