inputs:
  docker-password:
    required: true
  docker-username:
    required: true
  github-token:
    required: true
  image:
    required: true
  release:
    required: true
  latest:
    required: false
    type: boolean
    default: false
  push:
    required: false
    type: boolean
    default: false

runs:
  using: composite
  steps:
    -
      uses: kyzima-spb/gh-actions/.github/workflows/docker-build-image.yml@master
      with:
        context: ./docker/root
        file: ./docker/Dockerfile
        images: |
          ${{ inputs.image }}
          ghcr
        build-args: |
          RELEASE=${{ inputs.release }}
        tags: |
          ${{ inputs.release }}
        flavor: |
          latest=${{ inputs.latest }}
        cache: |
          arg=default,version=buildcache-${{ inputs.release }}
        push: ${{ inputs.push }}
      secrets:
        docker-username: ${{ inputs.docker-username }}
        docker-password: ${{ inputs.docker-password }}
        github-token: ${{ inputs.github-token }}
