on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      release:
        required: true
        type: string
      latest:
        required: false
        type: boolean
        default: false
      push:
        required: false
        type: boolean
        default: false

jobs:
  build:
    uses: kyzima-spb/gh-actions/.github/workflows/docker-build-image.yml@master
    with:
      context: ./docker/root
      file: ./docker/Dockerfile
      images: |
        ${{ inputs.image }}
        ghcr
      build-args: |
        RELEASE=${{ inputs.release }}
      tags: |
        ${{ inputs.release }}
      flavor: |
        latest=${{ inputs.latest }}
      cache: |
        arg=default,version=buildcache-${{ inputs.release }}
      push: ${{ inputs.push }}
    secrets:
      docker-username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
