on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      release:
        required: true
        type: string
      latest:
        required: false
        type: boolean
        default: false
      push:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and Push image
        uses: kyzima-spb/gh-actions/.github/actions/docker-build-image@master
        id: build
        with:
          context: ./docker/root
          file: ./docker/Dockerfile
          images: |
            ${{ inputs.image }}
            ghcr
          build-args: |
            RELEASE=${{ inputs.release }}
          tags: |
            ${{ inputs.release }}
          flavor: |
            latest=${{ inputs.latest }}
          cache: |
            arg=default,version=buildcache-${{ inputs.release }}
          push: ${{ inputs.push }}
          dockerhub-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          # github-username: ${{ github.repository_owner }}
          # github-password: ${{ secrets.GITHUB_TOKEN }}
          github-token: ${{ github.token }}

  delete-untagged:
    if: ${{ inputs.push }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Set GHCR_CONTAINER environment variable
        env:
          IMAGE: ${{ inputs.image }}
        run: echo "GHCR_CONTAINER=${IMAGE##*/}" >> $GITHUB_ENV
      -
        continue-on-error: true
        name: Deletes all untagged image versions
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: ${{ secrets.PAT }}
          user: ${{ github.repository_owner }}
          container: ${{ env.GHCR_CONTAINER }}
          untagged: true

  build-example:
    if: ${{ inputs.latest && inputs.push }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Set environment variables
        run: |
          GHCR_CONTAINER=chromium
          IMAGE_NAME="ghcr.io/$GITHUB_REPOSITORY_OWNER/$GHCR_CONTAINER"

          echo "GHCR_CONTAINER=$GHCR_CONTAINER" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "CACHE_IMAGE=$IMAGE_NAME:buildcache" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and Push example image
        uses: kyzima-spb/gh-actions/.github/actions/docker-build-image@master
        with:
          context: ./examples/chromium/root
          file: ./examples/chromium/Dockerfile
          images: ${{ env.IMAGE_NAME }}
          tags: latest
          cache: arg=default,repo=${{ env.IMAGE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Delete old versions of images
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: ${{ secrets.PAT }}
          user: ${{ github.repository_owner }}
          container: ${{ env.GHCR_CONTAINER }}
          untagged: true
