name: Check and build new Tixati version

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  branches:
    - dev-master

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: List files
      run: ls
