name: Check the new version of s6-overlay and upgrade

on:
  schedule:
    - cron: '45 5 * * *'
  push:
    branches:
      - master
      - dev-master
    paths:
      - .github/workflows/check-and-upgrade.yml

jobs:
  run:
    uses: kyzima-spb/gh-actions/.github/workflows/bump-version.yml@master
    secrets:
      github-token: ${{ secrets.PAT }}
    with:
      working-directory: ./docker
      commit-message: "Bump s6-overlay from {current} to {latest}"
      lookup: just-containers/s6-overlay
      get-current-release-command: |
        grep -oP '(?<=S6_OVERLAY_VERSION=")[^"]+' Dockerfile
      patch-files-command: |
        perl -i -pe 's|(?<=S6_OVERLAY_VERSION=")[^"]+|'${LATEST_VERSION}'|' Dockerfile
