name: Update Docker Hub Description

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/dockerhub-description.yml
      - README.md

jobs:
  dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ vars.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
