name: Build and publish images

on:
  push:
    branches:
      - master
      - dev-master
    paths:
      - '.github/actions/build-image/**'
      - .github/matrix.json
      - .github/workflows/publish-image.yml
      - 'docker/**'

jobs:
  setup:
    uses: kyzima-spb/gh-actions/.github/workflows/read-matrix.yml@master
    with:
      path: ./.github/matrix.json
  
  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and Publish Docker Image
        uses: ./.github/actions/build-image
        with:
          image: ${{ vars.IMAGE_NAME }}
          release: ${{ matrix.release }}
          latest: ${{ matrix.latest }}
          push: ${{ github.ref_name == 'master' }}
          docker-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
