name: CI to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - [bullseye-slim, true]
          - [buster-slim, false]
          - [stretch-slim, false]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            RELEASE=${{ matrix.release[0] }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gui:${{ matrix.release[0] }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/gui:${{ matrix.release[0] }}-buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/gui:${{ matrix.release[0] }}-buildcache,mode=max
      -
        name: Set latest tag
        if: ${{ matrix.release[1] }}
        run: |
          docker buildx imagetools create \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/gui:latest \
            ${{ secrets.DOCKER_HUB_USERNAME }}/gui:${{ matrix.release[0] }}
      -
        name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/gui:${{ matrix.release[0] }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/gui:${{ matrix.release[0] }}
      -
        name: Push latest image to GHCR
        if: ${{ matrix.release[1] }}
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/gui:latest \
            ${{ secrets.DOCKER_HUB_USERNAME }}/gui:${{ matrix.release[0] }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
