name: Chromium example

on:
  push:
    branches: dev-master
    paths:
      - examples/chromium
      - .github/workflows/publish-example.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./examples/chromium
          # file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/chromium:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/chromium:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/chromium:latest-buildcache,mode=max
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
