name: Build and publish images

on:
  push:
    branches:
      - master
      - dev-master
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/build-image.yml
      - .github/matrix.json
      - 'docker/**'

jobs:
  setup:
    uses: kyzima-spb/gh-actions/.github/workflows/read-matrix.yml@master
    with:
      path: ./.github/matrix.json

  build:
    needs: setup
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    uses: ./.github/workflows/build-image.yml
    with:
      image: ${{ vars.IMAGE_NAME }}
      release: ${{ matrix.release }}
      latest: ${{ matrix.latest }}
      push: ${{ github.ref_name == 'master' }}
    secrets: inherit
