name: CI to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - bullseye-slim
          - buster-slim
          - stretch-slim
    steps:
      -
        name: Check Out Repo
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            RELEASE=${{ matrix.release }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gui:${{ matrix.release }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/gui:${{ matrix.release }}-buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/gui:${{ matrix.release }}-buildcache,mode=max
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
