name: Test GitHub Actions

on:
  push:
    branches: [ actions-test ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - [bullseye-slim, tagname]
          - [buster-slim, tagname]
          - [stretch-slim, tagname]
        o:
          - key1: value2
          - key2: value2
    steps:
      - name: Result
        run: echo ${{ matrix.release[0] }} ${{ matrix.release[1] }}