name: Test GitHub Actions

on:
  push:
    branches: [ actions-test ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - [bullseye-slim, true]
          - [buster-slim, false]
          - [stretch-slim, false]
    steps:
      -
        name: Result
        run: echo ${{ matrix.release[1] }}
      -
        name: Run if latest
        if: ${{ matrix.release[1] }}
        run: echo "Is latest image"
