name: Test GitHub Actions

on:
  push:
    branches: [ actions-test ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - [bullseye-slim, [${{ secrets.DOCKER_HUB_USERNAME }}, latest]]
          - [bullseye-slim, [${{ secrets.DOCKER_HUB_USERNAME }}, bullseye-slim]]
          - [buster-slim, [${{ secrets.DOCKER_HUB_USERNAME }}, buster-slim]]
          - [stretch-slim, [${{ secrets.DOCKER_HUB_USERNAME }}, stretch-slim]]
    steps:
      - name: Result
        run: echo ${{ matrix.release[1][0] }}