name: Test GitHub Actions

on:
  push:
    branches: [ actions-test ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - [bullseye-slim, tagname]
          - [buster-slim, tagname]
          - [stretch-slim, tagname]
    steps:
      - name: Result
        run: echo ${{ matrix.release }}