name: Test GitHub Actions

on:
  push:
    branches: [ actions-test ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - [bullseye-slim, latest]
          - [bullseye-slim, bullseye-slim]
          - [buster-slim, buster-slim]
          - [stretch-slim, stretch-slim]
        o:
          - {key: value2}
    steps:
      - name: Result
        run: echo ${{ matrix.release[1][0] }}