on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      release:
        required: true
        type: string
      latest:
        required: false
        type: boolean
        default: false

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needRebuild: ${{ steps.check.outputs.result }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Check base Docker image
        id: check
        uses: kyzima-spb/docker-image-need-update-action@v1
        with:
          base-image: debian:${{ inputs.release }}
          user-image: ${{ inputs.image }}:${{ inputs.release }}

  rebuild:
    needs: check
    if: ${{ fromJSON(needs.check.outputs.needRebuild) }}
    uses: ./.github/workflows/build-image.yml
    with:
      image: ${{ inputs.image }}
      release: ${{ inputs.release }}
      latest: ${{ inputs.latest }}
      push: true
    secrets: inherit
